### PR TITLE
Adding Azure2Solace Codelab

### PR DESCRIPTION
**Pull request by sumeet-koshal**

### CODE REVIEW

**Comment by sumeet-koshal** [comment]
Adding azure2Solace codelab

**Comment by Mrc0113** [comment]
@TamimiGitHub can you generate the preview for tech review and checkout the formatting issues around numbering

**Comment by TamimiGitHub** [comment]
Thank you for subscribing to Tamimi's automated bot 🤖 Here is your preview link: https://deploy-preview-62--focused-beaver-3cc79d.netlify.app/

**Comment by TamimiGitHub** [comment]
To do: 
- Add Azure styling 
- Review number formatting issue

**Comment by TamimiGitHub** [comment]
- For https://github.com/solacese/azure2Solace 
-- Make public
-- Remove img dir
-- Update readme to refer to codelab 
-- Keep `SB2SolaceCSharp` and `SB2SolaceRest` code there
- In this directory, remove the `SB2SolaceCSharp` and `SB2SolaceRest` dirs
- Update duration for every section by adding `Duration: 0:0Y:00` under every `##` section where Y is the duration in minutes it’ll take to finish that section. Note, look at the `## Takeaways` section in the markdown file

**Pull request merged**
