### PR TITLE
Add deprecation warnings

### PR DESCRIPTION
**Pull request by Mrc0113**
Add deprecation warnings for Cloud Stream Codelabs that use Annotation based code.

### CODE REVIEW

**Comment by Mrc0113** [comment]
Thanks for opening up a PR and contributing to our open source codelabs! 

## Review process Guidelines
Once the PR is opened, tag **at least one** Technical Reviewer

### Technical Reviewer Responsibilities 
- [ ] Dry-run technical steps 
- [ ] Review technical positioning/messaging
- [ ] Point out typos and potential formatting issues
- [ ] Technical Reviewer(s): "Approve" or "Request Changes" by navigating to the `Files changed` tab and click on the "Review Changes" drop down    
Review Changes button

### Post Technical Review
A member of the Developer Advocate Team will review overall structure and merge into master which will push it to production

**Comment by Mrc0113** [comment]
@TamimiGitHub please review and make sure I didn't break anything. Note that although I made changes to the codelabs to mark them as deprecated I kept the old modification dates so the codelabs wouldn't be "Recent" when people use that to sort.

**Comment by TamimiGitHub** [comment]
Good call on marking them as deprecated; might do the same for the older boomi codelab. I reviewed and looks good to me 👌

**Review by TamimiGitHub — APPROVED** [review]

**Comment by Mrc0113** [comment]
Thanks @TamimiGitHub, I agree probably a good idea to do the same for the old Boomi Codelab.

**Pull request merged**
