### PR TITLE
Checkin to correct misleading Eg.

### PR DESCRIPTION
**Pull request by jaikratsinghtariyal**
In image its says q_rest_get but in Eg it says q_rdp_get. I was not following up images but the text given and wasted my 2-3 hours why the RD and Qs are not coming UP :)

### CODE REVIEW

**Comment by Mrc0113** [comment]
Thanks for making the update @tektutorial; and sorry it cost you so much time! 

@aaron-613 can you take a look at this and see if there are any other small changes that should be made as part of this? 
Looks like the markdown is updated so we'd just need to re-export the codelab as well.

**Comment by aaron-613** [comment]
Hey @Mrc0113 , the fix looks good, just a small typo.  I'm confused though, it says only 1 file has changed, the Markdown file, but the Netlify preview has the actual CodeLab updated as well.  I thought Netlify just took whatever had been exported, but doesn't look like files in the "codelabs" folder were touched..?

**Comment by TamimiGitHub** [comment]
Hey @aaron-613 - looks like the the actual codelab in the preview is not updated yet
Screen Shot 2021-08-09 at 11 57 15 AM

@tektutorial - thanks for your contribution and fixing the typo! To reflect the update on the production site, you will need to run the `export.sh` script found in the same dir of the markdown file you made the edit to, then add and commit the changes to the your branch which will update the PR. 

Note: you will have to have [go and claat installed](https://codelabs.solace.dev/codelabs/codelab-4-codelab/index.html?index#1) on our machine. If you had any issues with this please let me know, I can help you out or we can merge in your PR and I can do the export and push on my end. Thanks!

**Comment by TamimiGitHub** [comment]
I updated the codelab on master. Thanks again or catching this!

**Pull request closed without merging**
